version: "3.8"

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: blog_db
    restart: always
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
      POSTGRES_DB: blog_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- REDIS SERVICE ---
  redis-cache:
    image: redis:7-alpine
    container_name: blog_redis
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/blog_database
      SPRING_DATASOURCE_USERNAME: blog_user
      SPRING_DATASOURCE_PASSWORD: blog_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # --- REDIS CONNECTION ENV VARS ---
      SPRING_DATA_REDIS_HOST: redis-cache
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      - postgres-db
      - redis-cache

volumes:
  postgres_data:
